apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kerberosService: dn1
  name: dn1
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    kerberosService: dn1
status:
  loadBalancer: {}
