apiVersion: v1
kind: Service
metadata:
  labels:
    kerberosService: dn1
  name: dn1
spec:
  ports:
  - protocol: TCP
    port: 55555
    targetPort: 0
  selector:
    kerberosService: dn1
  type: ExternalName
  externalName: dn1.example.com