apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hdfs-dn1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hdfs-dn1
        kerberosService: kerberos
    spec:
      containers:
      - command:
        - /start-datanode.sh
        name: dn1
        image: hadoop-base:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: dn1-keytab
      restartPolicy: Always
      volumes:
      - name: dn1-keytab
        persistentVolumeClaim:
          claimName: server-keytab