apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kerberos
  labels:
    kerberosService: kerberos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hdfs-kerberos
        kerberosService: kerberos
    spec:
      containers:
      - command:
        - /start-kdc.sh
        name: kerberos
        image: hadoop-base:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: kerb-keytab
      restartPolicy: Always
      volumes:
      - name: kerb-keytab
        persistentVolumeClaim:
          claimName: server-keytab