apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kerberosService: kerberos
  name: kerberos
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    kerberosService: kerberos
status:
  loadBalancer: {}
