apiVersion: v1
kind: Service
metadata:
  labels:
    kerberosService: kerberos
  name: kerberos
spec:
  ports:
  - protocol: TCP
    port: 55555
    targetPort: 0
  selector:
    kerberosService: kerberos
  type: ExternalName
  externalName: kerberos.example.com
