apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nn
  labels:
    kerberosService: nn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hdfs-nn
        kerberosService: nn
    spec:
      containers:
      - command:
        - /start-namenode.sh
        name: nn
        ports:
        - containerPort: 9000
        image: hadoop-base:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/keytabs
          name: nn-keytab
        - mountPath: /hadoop
          name: nn-hadoop
      restartPolicy: Always
      volumes:
      - name: nn-keytab
        persistentVolumeClaim:
          claimName: server-keytab
      - name: nn-hadoop
        persistentVolumeClaim:
          claimName: nn-hadoop
