apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hdfs-nn
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - command:
        - /start-namenode.sh
        name: nn
        ports:
        - containerPort: 9000
        image: hadoop-base:latest
        volumeMounts:
        - mountPath: /var/keytabs
          name: server-keytab
        - mountPath: /hadoop
          name: nn-server
      restartPolicy: Always
      volumes:
      - name: server-keytab
        persistentVolumeClaim:
          claimName: server-keytab
      - name: nn-server
        persistentVolumeClaim:
          claimName: nn-server
